### PR TITLE
Example notebook for catalog generation

### PR DESCRIPTION
**Pull request by yetinam**
Hey @jawooll ,
I though it would be nice to have an example on how to create a catalog for SeisBench using some associator. And as I anyhow wanted to play around with phase association a bit, I took the chance and create the example using GaMMA. I think this will also be helpful for people with similar issues as in #82. Could you have a look over the PR and comment what you think about the example? As study region I went to my canonical example, i.e., Iquique aftershocks.

### CODE REVIEW

**Comment by jawooll** [comment]
Hey Jannes, I like the idea! I'll take a look.

**Comment by yetinam** [comment]
I pushed a new version, now only taking 12 hours of data it. Tested it on Colab with and without GPU. The longest waiting time (2 or 3 minutes) was actually for downloading the data from GEOFON.

**Comment by jawooll** [comment]
Ok, it looks good to me. As we can't do the usual line-by-line highlighting as it is a notebook, I'll just post some additional suggestions here:

1. When creating the pick_df, does the phase have to be a lowercase string for input into GaMMa? If not, would it be possible to keep this capitalized?
2. Just close off the epicentral map plot with plt.show()
3. For the final plot of the waveforms, we could actually plot the y-axis as source-station distance - to back up your commentary - once you select an event, compute the distance to each station, this will be in the same row-order as the station_df, so you can then just use this as the y-axis instead of the Northing. 

The rest looks good!

**Review by jawooll — CHANGES_REQUESTED** [review]
See comment above.

**Comment by yetinam** [comment]
For 1., yes, unfortunately this is necessary for GaMMA. I'll address the other points. Good idea with the source-station distance!

**Comment by yetinam** [comment]
I pushed a new version incorporating the suggested changes (2 and 3). Could you have a look?

**Comment by jawooll** [comment]
Hey, thanks for the quick turnaround, it's basically there now. The final axis label just needs to be changed too to distance now instead of northing. 

If you would like to, we can automate the cuda backend check:

```python
if torch.cuda.is_available():
    picker.cuda()
```

But these are now both very minor, after this I say we are good to merge.

**Comment by yetinam** [comment]
Sounds good! I'll implement the changes tomorrow.

**Comment by yetinam** [comment]
I integrated the changes now.

**Comment by jawooll** [comment]
All looks good, thanks for this. Merging now.

**Comment by yetinam** [comment]
Thanks for the thorough reviewing!

**Pull request merged**
