### PR TITLE
Add PNW dataset to SeisBench

### PR DESCRIPTION
**Pull request by niyiyu**
Hi @yetinam,

As the PNW paper just published this week on *Seismica*, I am adding opening this PR so that the dataset can be accessed through SeisBench. Given that the dataset already follows seisbench format, there require really minimal scripts. 

We are currently making two copies of the dataset, one on Google Drive, another on a server in the campus. It would be great you could mirror it.

ComCat dataset.
  - waveform (62.7 GB): [[GDrive](https://drive.google.com/file/d/10UCLyJSRibvhon9CuUTfns3fObNFKDer/view?usp=sharing)] | [[UW-ESS](http://dasway.ess.washington.edu/niyiyu/PNW-ML/comcat_waveforms.hdf5)]
  - metadata (50.4 MB): [[GDrive](https://drive.google.com/file/d/1bKDITx8KiDGZUaUoWQSZilpo7GhdWxKv/view?usp=sharing)] | [[UW-ESS](http://dasway.ess.washington.edu/niyiyu/PNW-ML/comcat_metadata.csv)]

Let me know if there is any problem with the pnw.py that I can further improve. Thanks!

Yiyu

### CODE REVIEW

**Comment by yetinam** [comment]
Hi @niyiyu ,

congratulations to the paper and thanks for the PR! I'm currently traveling, so it might take a few days until I get to it. But on the first glance the PR already looks pretty good.

**Comment by yetinam** [comment]
Okay, I had a look through it. It looks pretty good and I only have a few minor points.

- I think it would be great if you'd add the other parts of the PNW dataset too. Accelerometers, noise and exotic events are all quite interesting. Maybe just create additional classes like `PNWNoise`, `PNWAccelerometers`, and `PNWExotic`. I'll adjust the file structure accordingly on the server that it identifies the right files.
- Could you add the PNW dataset to the documentation. It should be on the [overview page](https://github.com/seisbench/seisbench/blob/main/docs/pages/benchmark_datasets.rst) (datasets in alphabetic order, best case with a figure. I think the figure from your Github would be great) and on the [reference page](https://github.com/seisbench/seisbench/blob/main/docs/pages/documentation/data.rst). It's a bit redundant and I'd eventually like to restructure the documentation completely but I don't foresee this happening anytime soon.
- I think you can remove the warning in line 32 completely.

I'm currently on a slow internet connection, so I haven't looked at the data yet. I'll mirror it to our server once I'm back with faster internet.

**Comment by niyiyu** [comment]
OK. I've updated this PR. let me know how it looks like : )

**Comment by yetinam** [comment]
Merged it. You can find the data on our mirror now, in case you want to link it as an option in your repository too. Thanks again for providing this great dataset!

**Comment by niyiyu** [comment]
Thanks!! Glad to contribute!

**Pull request merged**
