### PR TITLE
add CREW

### PR DESCRIPTION
**Pull request by albertleonardo**
Add the Curated Regional Earthquake Waveforms dataset from Aguilar & Beroza, 2024

### CODE REVIEW

**Comment by yetinam** [comment]
Thanks for submitting the PR! I'll test it, probably do some small modifications and then merge.

**Comment by yetinam** [comment]
Failing tests are unrelated and come from an [obspy dependency issue](https://github.com/obspy/obspy/issues/3484).

**Comment by yetinam** [comment]
I now had a look at the PR and did a few small modifications. In particular, I added CREW to the documentation. Please have a look at it and say if that's fine with you. I've used your abstract and a figure from your Seismica paper for the documentation. Is that okay with you? Once the CI passed and you confirmed my modifications, I'll merge the PR. Thanks again for your effort put into this contribution!

**Comment by yetinam** [comment]
Rebased onto main after merging #306

**Comment by albertleonardo** [comment]
Hello Jannes,

It looks good, I am fine with it. Thanks for helping me out with this!


________________________________

**Pull request merged**
