### PR TITLE
Fix amplitude normalization in PhaseNet(Light) and EQTransformer (Closes #187)

### LINKED ISSUE #187: Inconsistent normalization strategies
The data normalization strategies between annotate, the original implementation (and weights), and the benchmark derived weights is not always identical. This can lead performance degradation. The table below shows the strategies.

|               | Original | Benchmark | annotate |
|---------------|----------|-----------|----------|
| EQTransformer | std      | peak      | std      |
| PhaseNet      | std      | peak      | std      |
| GPD           | peak     | peak      | peak     |

To fix the issue, the choice of normalization in `annotate` should be made dynamic.

This was originally detected in #186 but is kept in this issue report for better tracking.

### PR DESCRIPTION
**Pull request by yetinam**
See linked issue for description.

I'll updated the corresponding weights in the repository while the CI is running.

### CODE REVIEW

**Comment by yetinam** [comment]
Weights are updated in the repository now. Furthermore, there is now a warning if older weight versions with incorrect normalization are used. Waiting for the CI to pass and will merge then.

**Comment by zhong-yy** [comment]
Hi @yetinam, loading the updated weight will give an error `ValueError: Weights require seisbench version at least 0.3.2, but the installed version is 0.3.1.dev11+g9b24b60.`

**Comment by yetinam** [comment]
Hi @zhong-yy ,
This happens only on the dev version installed from source. Just run `pip install -e .` again in the repository after pulling the latest changes and it should run. (If it doesn't on main, you might have to run the command while on the maintenance branch. You can safely switch back to main after.)

**Comment by zhong-yy** [comment]
Thank you. There are 3 maintenance branches; to be safe, I prefer to stay in main. I tried install from `pip install seisbench`. Although the version number is 0.3.2,  it seems not the latest code. Finally I just set `seisbench.__verison__="0.3.2"`.

**Pull request merged**
